name       : python-llfuse
version    : 1.3
release    : 2
source     :
    - https://bitbucket.org/nikratio/python-llfuse/downloads/llfuse-1.3.tar.bz2 : d1ab2c7cdaeed1c4c99882f2ad44df3906db263b832d76de18291e484c685bd2
license    : LGPL-2.1
component  : programming.python
summary    : Python bindings for the low-level FUSE API
description: |
    Python-LLFUSE is a set of Python bindings for the low level FUSE API.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(python3)
    - attr-devel
build      : |
    %python3_setup
install    : |
    %python3_install
