name       : python-llfuse
version    : 1.4.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/b1/d4/44443fbaac6d5b878da99e7c0948ee93c7934fa3b00e48c5363823b583d0/llfuse-1.4.1.tar.gz : c29c79d96a5aeab51608cae12594a1bf83576d86232f97341c7f779d413a4ec9
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python bindings for the low-level FUSE API
description: |
    Python-LLFUSE is a set of Python bindings for the low level FUSE API.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(python3)
    - attr-devel
build      : |
    %python3_setup
install    : |
    %python3_install
