name       : python-llfuse
version    : 1.3.6
release    : 6
source     :
    - https://files.pythonhosted.org/packages/75/b4/5248459ec0e7e1608814915479cb13e5baf89034b572e3d74d5c9219dd31/llfuse-1.3.6.tar.bz2 : 31a267f7ec542b0cd62e0f1268e1880fdabf3f418ec9447def99acfa6eff2ec9
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python bindings for the low-level FUSE API
description: |
    Python-LLFUSE is a set of Python bindings for the low level FUSE API.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(python3)
    - attr-devel
build      : |
    %python3_setup
install    : |
    %python3_install
