name       : python-llfuse
version    : 1.4.2
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/l/llfuse/llfuse-1.4.2.tar.gz : ea4d19297be0ddbc5db68b421aa649c737a351f9c809919385a118c217c33083
homepage   : https://github.com/python-llfuse/python-llfuse/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python bindings for the low-level FUSE API
description: |
    Python-LLFUSE is a set of Python bindings for the low level FUSE API.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libattr)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
